make: ex_compile.c word_counter.c
	gcc -o ex-compile ex_compile.c -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/glib-2.0/include -lglib-2.0
	gcc -o word_counter word_counter.c -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/glib-2.0/include -lglib-2.0